version: "3.7"

services:
    # image project
    laravel_9:
    # app:
        # container_name: meuprojeto-laravel
        build:
            args:
                user: bruno
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: meuprojeto/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        # container_name: meuprojeto-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        # container_name: meuprojeto-mysql
        image: mysql:8.0
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel

    # queue
    queue:
        # container_name: meuprojeto-queue
        # image: meuprojeto/laravel-app
        # restart: unless-stopped
        # command: "php artisan queue:work"
        # volumes: 
        #     - ./:/var/www
        # depends_on: 
        #     - redis
        #     - app
        # networks: 
        #     - laravel
        build:
            args:
                user: bruno
                uid: 1000
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work" 
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel           
                
    # redis
    redis:
        # container_name: meuprojeto-redis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge